NODE_DEFAULTS: dict[str, dict[str, object]] = {
    "WAIT": {"TIME": 1},
    "SKILL": {
        "MOVE": "Divergent Fist",
        "SPEED": 1,
        "START": 0,
        "HOLD FOR": 0,
        "ENABLE VARIANTS": True,
        "CANCEL LAST": False,
    },
    "SPECIAL": {
        "SPEC": "Limitless",
        "SPEED": 1,
        "ENABLE VARIANTS": True,
        "CANCEL LAST": False,
    },
    "ANIM": {
        "ANIM_USE": [1, 1],
        "PREVIEW": [0, 3.6],
        "SPEED": 1,
        "FADE IN": 0.1,
        "FADE OUT": 0,
        "LAST HIT": -1,
        "LOOPED": False,
    },
    "SFX": {
        "ID": 12222253,
        "START": 0,
        "END": 500,
        "SPEED": 1,
        "VOLUME": 1,
        "FADE IN": 0,
        "FADE OUT": 0,
        "GLOBAL": False,
        "PROJECTILE TAG": "nil",
        "CANCEL": False,
    },
    "VELO": {
        "FORCE": "0, 0, 0",
        "TIME": 0,
        "FADE": False,
        "TRACK": False,
        "LAST HIT": -1,
        "RAGDOLL": 0,
        "TRUE RAGDOLL": False,
        "RELATIVE FROM BRANCH": False,
    },
    "CONNECT": {"SIGNAL": "Nothing", "TIME": 0.1, "RANGE": 99999999},
    "HITBOX": {
        "POSITION": "0, 0, 4",
        "ROTATION": "0, 0, 0",
        "SIZE": "6, 6, 6",
        "STUN": 1,
        "STUN ANIM": False,
        "DAMAGE": 1,
        "DEBREE": 0,
        "ATTACK TYPE": "Melee",
        "BLOCKABLE": True,
        "360 BLOCK": False,
        "CANCEL ENEMY": True,
        "CLEAR KNOCKBACK": False,
        "CAN KILL": True,
        "HIT RAGDOLL": False,
        "HIT USER": False,
        "SINGLE TARGET": True,
        "BRANCH": "nil",
        "BRANCH TARGET": "nil",
        "BRANCH FINISHER": "nil",
        "PROJECTILE TAG": "nil",
        "IGNORE WAKEUP": False,
        "PREVIEW": [0, 15],
    },
    "BRANCH": {"BRANCH": "nil", "RANDOM": "", "LAST HIT": -1},
    "VISUAL": {
        "EFFECT": "Slash",
        "TIME": 1,
        "POSITION": "0, 0, 0",
        "ROTATION": "0, 0, 0",
        "SIZE": 1,
        "COLOR": "255, 255, 255",
        "OPACITY": 0,
        "ALT POSITION": "0, 0, 0",
        "ALT ROTATION": "0, 0, 0",
        "ALT SIZE": 1,
        "ALT COLOR": "255, 255, 255",
        "ALT OPACITY": 0,
        "TEXTURE": 2,
        "BODY PART": "HumanoidRootPart",
        "EASING STYLE": "Linear",
        "EASING DIRECTION": "In",
        "PROJECTILE TAG": "nil",
        "VISUAL TAG": "nil",
        "AMOUNT": 1,
        "RUN ON SERVER": False,
        "RELATIVE FROM BRANCH": False,
        "CANCEL ON INTERRUPT": False,
        "CAN COLLIDE": False,
        "LAST HIT": -1,
    },
    "GRAB": {
        "BODY PART": "HumanoidRootPart",
        "BODY PART2": "HumanoidRootPart",
        "TIME": 1,
        "POSITION": "0, 0, 0",
        "ROTATION": "0, 0, 0",
        "LAST HIT": 1,
    },
    "PROJECTILE": {
        "DAMAGE": 1,
        "STUN": 1,
        "SPEED": 1,
        "SIZE": "6, 6, 6",
        "POSITION": "0, 0, 0",
        "ROTATION": "0, 0, 0",
        "ATTACK TYPE": "Melee",
        "PROJECTILE TAG": "nil",
        "REFLECT COUNT": 0,
        "FILTER INTERVAL": 1,
        "BRANCH": "nil",
        "BRANCH TARGET": "nil",
        "BRANCH COLLIDED": "nil",
        "CONTINUE": False,
        "HIT RAGDOLL": False,
        "STUN ANIM": False,
        "HIT USER": False,
        "BLOCKABLE": True,
        "AIM LAST HIT": -1,
        "TIME": 1,
        "IGNORE WAKEUP": True,
        "DEBREE": 0,
        "CANCEL ENEMY": True,
        "CACHE": True,
        "CLEAR KNOCKBACK": False,
    },
    "COUNTER": {
        "TIME": 1,
        "STUN": 1,
        "ATTACK TYPE2": "Melee",
        "BRANCH": "nil",
        "BRANCH TARGET": "nil",
        "CANCEL ENEMY": True,
        "REMOVE ON HIT": True,
    },
    "TAG": {
        "TAG": "nil",
        "VALUE": "nil",
        "TIME": 1,
        "ADD/REMOVE": True,
        "CHECK": False,
        "SET": True,
        "BRANCH": "nil",
        "LAST HIT": -1,
    },
    "STATE": {
        "STATE": "Stun",
        "VALUE": 1,
        "TIME": 1,
        "DISABLE BURST": False,
        "CANCEL ON END": False,
        "LAST HIT": -1,
        "BRANCH": "nil",
        "CHECK": False,
    },
    "TELEPORT": {
        "POSITION": "0, 0, 0",
        "ROTATION": "0, 0, 0",
        "PROJECTILE TAG": "nil",
        "LAST HIT": -1,
        "RELATIVE FROM BRANCH": False,
    },
    "ULTGIB": {"AMOUNT": 5},
    "HPGIB": {"AMOUNT": 5},
    "EVGIB": {"AMOUNT": 5},
    "HITCNCL": {"TIME": 1, "ENDLAG": 1, "BRANCH": "nil", "FLIP": False},
    "SETCD": {"KEY": -1, "COOLDOWN": -1},
    "LOOP": {"LOOP BACK": 1, "HOLD": False, "LOOP AMOUNT": 3},
}


PROPERTIES_DEFAULTS = {
    "DMG": 1,
    "KNOCK": 1,
    "INV": False,
    "REP": False,
    "REP2": False,
    "AWK": False,
    "KEEP": False,
    "AWK2": False,
    "USE": False,
    "USEONDEATH": False,
    "NOSTUN": False,
    "NOCANCEL": False,
    "VAR": "-",
}

CONDITIONS_DEFAULTS = {
    "AIR": {"FLIP": False},
    "JUMP": {"FLIP": False},
    "AIM": {"FLIP": False},
    "ULT": {"FLIP": False},
    "BAR": {"AMOUNT": 2, "FLIP": False},
    "DUR": {"DURABILITY": 1},
    "HP": {"AMOUNT": 1, "FLIP": False},
    "DOMAIN": {"FLIP": False},
    "HOLD": {"FLIP": False},
}
